import pandas as pd
import numpy as np

# Create a numpy array
data = np.array([[1,2,3],
                 [5,6,7],
                 [9,10,11]])

# Convert the numpy array to a pandas DataFrame
df = pd.DataFrame(data, columns= ['Column1', 'Column2', 'Column3'])

# Replace all occurrences of 5 with NaN
df = df.replace(5, np.nan)

# Fill all NaN values with 0
df = df.fillna(0)
# Drop all rows with NaN values
df = df.dropna()

# Add a new column to the DataFrame with values generated by numpy
df['Column4'] = np.arange(len(df))

# Print the DataFrame
print(df)